stages:
  - test
  - build
  - push

test-job: 
  stage: test
  script:
    - dotnet test Tests/Tests.csproj

build-job:
  stage: build
  variables:
   CR_ID: crp1ihdipp8l3cf2k9c0
  script: 
    - /bin/bash ./build.sh

push-job:
  stage: push
  variables:
   CR_ID: crp1ihdipp8l3cf2k9c0
  script: 
    - docker push cr.yandex/$CR_ID/web
