stages:
  - code style check
  - test
  - build
  - push

include:
  - template: Code-Quality.gitlab-ci.yml


code-quality:
  stage: code style check
  artifacts:
    paths: [gl-code-quality-report.json]

test-job: 
  stage: test
  script:
    - dotnet test SmartHomeManager/Tests.csproj

build-job:
  stage: build
  script: 
    - /bin/bash ./build.sh
