version: "3"
services:
    web:
        build: ./SmartHomeManager
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes:
            - ./appsettings.prod.json:/app/appsettings.prod.json
        environment:
            ASPNETCORE_ENVIRONMENT: "prod"
    db:
        image: "mcr.microsoft.com/mssql/server"
        volumes:
           - backend_db:/var/opt/mssql
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "7000:1433"
volumes:
  backend_db: