version: "3"
services:
    web:
        build: 
            context: ./SmartHomeManager
            args:
                - GIT_COMMIT=123
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes:
            - ./appsettings.prod.json:/app/appsettings.prod.json
        env_file:
            - app.env
    db:
        image: "mcr.microsoft.com/mssql/server"
        volumes:
           - backend_db:/var/opt/mssql
        env_file:
            - db.env
        ports:
            - "7000:1433"
volumes:
  backend_db: