version: "3"
services:
    web:
        build: 
            context: ./SmartHomeManager
            args:
                - GIT_COMMIT=${GIT_COMMIT}
                - CUR_DATE=${CUR_DATE}
        image: cr.yandex/${CR_ID}/web
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes:
            - ./appsettings.prod.json:/app/appsettings.prod.json
        env_file:
            - app.env
        healthcheck:
          test: curl -sS http://127.0.0.1/health || echo 1
          interval: 5s
          timeout: 10s
          retries: 3
    db:
        image: "mcr.microsoft.com/mssql/server"
        volumes:
           - backend_db:/var/opt/mssql
        env_file:
            - db.env
        ports:
            - "7000:1433"
volumes:
  backend_db: