apiVersion: v1
kind: Namespace
metadata:
  name: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: manager
spec:
  selector:
    matchLabels:
      app: manager
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
        - image: cr.yandex/crp1ihdipp8l3cf2k9c0/web:latest
          name: manager 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: manager
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: manager
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: manager
  namespace: manager
spec:
  rules:
    - host: testo.stage.code.hits.university
      http:
        paths:
          - backend:
              serviceName: manager
              servicePort: 8080
            path: /
            pathType: Prefix